// @koala-append "MIDIStream.js"
// @koala-append "MIDIFile.js"
// @koala-append "MIDITrack.js"
// @koala-append "MIDIEvent.js"
// @koala-append "MIDIMetaEvent.js"
// @koala-append "MIDISysExEvent.js"
// @koala-append "MIDIControlEvent.js"
// @koala-append "MIDIInstrument.js"